"""empty message

Revision ID: 8841acddcdad
Revises: ff9ce18c65d8
Create Date: 2021-04-28 16:49:59.429168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8841acddcdad'
down_revision = 'ff9ce18c65d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'lokies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('lokies', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
