"""empty message

Revision ID: ff9ce18c65d8
Revises: a4e2b05931cf
Create Date: 2021-04-28 16:48:04.414331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9ce18c65d8'
down_revision = 'a4e2b05931cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('lokies', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'lokies')
    # ### end Alembic commands ###
